#/usr/bin/python3

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with $1$ and $2$, the first $10$ terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms

'''
def fibonacci_even_sum(number):
    even_nums = []
    all_nums = []
    x = 1
    y = 2
    z = x + y

    all_nums.append(x)
    all_nums.append(y)
    all_nums.append(z)
  
    even_nums.append(y)
    
    while z < number:        
        # x = y
        # y = z
        x, y = y, z
        z = x + y 

        all_nums.append(z)
        if z % 2 == 0:
             even_nums.append(z)        
    print(all_nums)
    print(even_nums)
    return sum(set(even_nums))

print(f'the SUM of all even numbers is {fibonacci_even_sum(4000000)}')




